config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'users/index'
  root 'maps#view'
  get 'maps/view'

end

app/models/user.rb
class User < ActiveRecord::Base
    geocoded_by :address
    after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def view
     @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
       marker.infowindow user.description
       marker.picture({
       "url" => "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
       "width" =>  32,
       "height" => 32})
       marker.json({ title: user.title })
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
       marker.infowindow user.description
       marker.picture({
       "url" => "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
       "width" =>  32,
       "height" => 32})
       marker.json({ title: user.title })
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

 
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Geolocator</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%= link_to 'Home', maps_view_path %></li>
        <li><%= link_to 'Add User', new_user_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
     
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin<span class="caret"></span></a>
          <ul class="dropdown-menu">
                <li><a href="#">Settings</a></li>
                <li><a href="#">Add User</a></li>
                <li><a href="#">Admin Dashboard</a></li>
                <li><a href="#">Login</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/maps/view.html.erb
<script src="//maps.google.com/maps/api/js?key=AIzaSyALGjkDHFbTAPcE80K34zJmFdo1dRBULCk"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div>
  <div id="map"></div>
</div>
<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
});
</script>

app/views/users/_form.html.erb
<div class="container">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
      <div class="input-group">
        <%= f.label :latitude,"Latitude:", class: 'col-md-4 control-label' %><br>
         <divclass="col-md-8">
           <%= f.text_field :latitude,class: "form-control" %><br>
         </div>
      </div>
      <br>
      
      <div class="input-group">
        <%= f.label :longitude,"Longitude:", class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= f.text_field :longitude,class: "form-control" %><br>
        </div>
      </div>
       <br>
       
      <div class="input-group">
        <%= f.label :address,"Address:", class: 'col-md-4 control-label'  %>
        <div class="col-md-8">
          <%= f.text_field :address,class: "form-control" %><br>
        </div>
      </div>
       <br>
       
      <div class="input-group">
        <%= f.label :description,"Description:", class: 'col-md-4 control-label'  %>
        <div class="col-md-8">
          <%= f.text_area :description,class: "form-control" %><br>
        </div>
      </div>
       <br>
       
      <div class="input-group">
        <%= f.label :title ,"Title:", class: 'col-md-4 control-label' %>
        <div class="col-md-8">
          <%= f.text_field :title ,class: "form-control"%><br>
        </div>
      </div>
       <br>
       
       <div class="form-group">
         <div class="controls">
        <%= f.submit %>
      </div>
       </div>
   </fieldset>
 <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="">
<h1>Listing Users</h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><strong><em>Latitude</em></strong></th>
      <th><strong><em>Longitude</em></strong></th>
      <th><strong><em>Address</em></strong></th>
      <th><strong><em>Description</em></strong></th>
      <th><strong><em>Title</em></strong></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.latitude %></td>
        <td><%= user.longitude %></td>
        <td><%= user.address %></td>
        <td><%= user.description %></td>
        <td><%= user.title %></td>
        <td><%= link_to 'Show', user ,:class => 'btn btn-info' %></td>
        <td><%= link_to 'Edit', edit_user_path(user),:class => 'btn btn-success' %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },:class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path ,class: 'btn btn-link' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @user.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @user.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @user.title %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', maps_view_path %>